import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { CartProvider } from "@/context/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "S W E E T - B A K E R Y",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          {/* Navbar */}
          <div className="relative w-full">
            <Navbar />
          </div>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
